environment:
  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\appveyor.bat'

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

deploy: off
