/* libmypaint - The MyPaint Brush Library
 * Copyright (C) 2019 The MyPaint Team
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */


/* ONLY TO BE USED FOR INTERNAL IMPLEMENTATIONS, DO NOT MOVE TO ANY PUBLIC HEADER */
typedef enum {
    DAB_PARAM_OPAQUE,
    DAB_PARAM_HARDNESS,
    DAB_PARAM_ALPHA_ERASER,
    DAB_PARAM_ASPECT_RATIO,
    DAB_PARAM_ANGLE,
    DAB_PARAM_LOCK_ALPHA,
    DAB_PARAM_COLORIZE,
    DAB_PARAM_POSTERIZE,
    DAB_PARAM_POSTERIZE_NUM,
    DAB_PARAM_PIGMENT_FACTOR,
    DAB_NUM_PARAMS,
} DabFloatParamsOrder;
